---
# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

version: 2

run:
  timeout: 5m
  tests: true
  go: '1.24'  # Use Go 1.24 for linting to avoid version mismatch

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Static analysis (includes gosimple)
    - unused         # Check for unused code
    - misspell       # Check for misspelled words
    - revive         # Fast, configurable, extensible linter

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
