---
name: 'grype_me'
description: 'An easy to use Action to scan the supply chain of your project for known vulnerabilities using Anchore Grype and generate badges.'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  # === Repository-based scanning (scan git refs) ===
  scan:
    description: >-
      Scan a git ref in the repository. Mutually exclusive with image/path/sbom.
      - 'latest_release': (default) Scan the highest stable semver tag.
        Pre-release tags (e.g., v1.0.0-beta) are skipped. Ideal for nightly
        vulnerability scans of your latest published release.
      - 'head': Scan the current working directory as checked out (no git
        operations). Use this for PR checks or when you control the checkout.
      - A tag/branch name: Scan a specific git ref.
      Note: For latest_release, tags are sorted by semantic version, not date.
    required: false
    default: ''

  # === Artifact-based scanning (mutually exclusive with 'scan') ===
  image:
    description: >-
      Container image to scan (e.g., 'myapp:latest', 'ghcr.io/org/app:v1.2.3').
      The image must be available locally (pulled or built) or in a registry.
      Mutually exclusive with scan/path/sbom.
    required: false
    default: ''
  path:
    description: >-
      Directory or file path to scan (e.g., '.', './dist', './target/app.jar').
      Grype auto-detects the content type (go.mod, package.json, JAR, etc.).
      Mutually exclusive with scan/image/sbom.
    required: false
    default: ''
  sbom:
    description: >-
      SBOM file to scan (Syft JSON, SPDX, or CycloneDX format).
      Generate with 'syft' or 'anchore/sbom-action' first.
      Mutually exclusive with scan/image/path.
    required: false
    default: ''

  # === Common options ===
  fail-build:
    description: >-
      Fail the action if vulnerabilities are found at or above severity-cutoff.
    required: false
    default: 'false'
  severity-cutoff:
    description: >-
      Minimum severity to trigger a failure when fail-build is true.
      One of: negligible, low, medium, high, critical.
    required: false
    default: 'medium'
  output-file:
    description: 'Path to save grype''s JSON scan results (optional)'
    required: false
    default: ''
  variable-prefix:
    description: >-
      Prefix for environment variable names (default: "GRYPE_")
    required: false
    default: 'GRYPE_'
  only-fixed:
    description: >-
      Only report vulnerabilities that have a fix available.
    required: false
    default: 'false'
  db-update:
    description: >-
      Update the vulnerability database before scanning. The image ships with
      a pre-downloaded DB (max 24h old). Set to 'true' for critical scans
      requiring the absolute latest data. Default: 'false' (use built-in DB).
    required: false
    default: 'false'
  debug:
    description: >-
      Enable debug output (prints environment variables when true).
      Warning: may expose sensitive data in logs.
    required: false
    default: 'false'
  badge-label:
    description: >-
      Label text for the generated shields.io badge URL.
      Default: auto-generated as '✊ grype_me <mode>', where
      <mode> is 'release', 'head', 'image', or 'path'.
      Set to override with custom text.
      Underscores and hyphens must be escaped for proper
      rendering by shields.io.
    required: false
    default: ''

outputs:
  grype-version:
    description: 'Version of Grype used for scanning'
  db-version:
    description: 'Version of the Grype vulnerability database'
  cve-count:
    description: 'Total number of CVEs found'
  critical:
    description: 'Number of critical severity vulnerabilities'
  high:
    description: 'Number of high severity vulnerabilities'
  medium:
    description: 'Number of medium severity vulnerabilities'
  low:
    description: 'Number of low severity vulnerabilities'
  json-output:
    description: 'Path to the JSON output file (if output-file was specified)'
  badge-url:
    description: >-
      shields.io URL to create a badge showing a vulnerability summary.
      Color indicates severity: green (none), yellowgreen (low),
      yellow (medium), orange (high), red (critical).

runs:
  using: 'docker'
  image: 'docker://ghcr.io/tomtonic/grype_me:v1'
