---
name: 'grype_me'
description: >-
  Scan repositories or artifacts with Anchore Grype; publish vulnerability
  badges and linked Markdown reports.
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  # === Repository-based scanning (scan git refs) ===
  scan:
    description: >-
      Scan a git ref in the repository. Mutually exclusive with image/path/sbom.
      - 'latest_release': (default) Scan the highest stable semver tag.
        Pre-release tags (e.g., v1.0.0-beta) are skipped. Ideal for nightly
        vulnerability scans of your latest published release.
      - 'head': Scan the current working directory as checked out (no git
        operations). Use this for PR checks or when you control the checkout.
      - A tag/branch name: Scan a specific git ref.
      Note: For latest_release, tags are sorted by semantic version, not date.
    required: false
    default: ''

  # === Artifact-based scanning (mutually exclusive with 'scan') ===
  image:
    description: >-
      Container image to scan (e.g., 'myapp:latest', 'ghcr.io/org/app:v1.2.3').
      The image must be available locally (pulled or built) or in a registry.
      Mutually exclusive with scan/path/sbom.
    required: false
    default: ''
  path:
    description: >-
      Directory or file path to scan (e.g., '.', './dist', './target/app.jar').
      Grype auto-detects the content type (go.mod, package.json, JAR, etc.).
      Mutually exclusive with scan/image/sbom.
    required: false
    default: ''
  sbom:
    description: >-
      SBOM file to scan (Syft JSON, SPDX, or CycloneDX format).
      Generate with 'syft' or 'anchore/sbom-action' first.
      Mutually exclusive with scan/image/path.
    required: false
    default: ''

  # === Common options ===
  fail-build:
    description: >-
      Fail the action if vulnerabilities are found at or above severity-cutoff.
    required: false
    default: 'false'
  severity-cutoff:
    description: >-
      Minimum severity to trigger a failure when fail-build is true.
      One of: negligible, low, medium, high, critical.
    required: false
    default: 'medium'
  output-file:
    description: 'Path to save grype''s JSON scan results (optional)'
    required: false
    default: ''
  only-fixed:
    description: >-
      Only report vulnerabilities that have a fix available.
    required: false
    default: 'false'
  db-update:
    description: >-
      Update the vulnerability database before scanning. The image ships with
      a pre-downloaded DB (max 24h old). Set to 'true' for critical scans
      requiring the absolute latest data. Default: 'false' (use built-in DB).
    required: false
    default: 'false'
  debug:
    description: >-
      Enable debug output (prints environment variables when true).
      Warning: may expose sensitive data in logs.
    required: false
    default: 'false'
  gist-token:
    description: >-
      A GitHub personal access token (classic) with 'gist' scope.
      Required for uploading the badge JSON and scan report to a gist.
      Store as a repository secret (e.g., secrets.GIST_TOKEN).
    required: false
    default: ''
  gist-id:
    description: >-
      The ID of the gist to update with badge JSON and scan report.
      Create a gist manually, then copy the ID from the URL
      (e.g., https://gist.github.com/user/<this-id>).
      Required when gist-token is set.
    required: false
    default: ''
  gist-filename:
    description: >-
      Base filename for files stored in the gist. The action will create
      two files: '<name>-badge.json' (shields.io endpoint) and
      '<name>-report.md' (detailed scan report). If empty, the scan
      mode is used (e.g., 'release-badge.json', 'release-report.md').
    required: false
    default: ''

outputs:
  grype-version:
    description: 'Version of Grype used for scanning'
  db-version:
    description: 'Version of the Grype vulnerability database'
  cve-count:
    description: 'Total number of CVEs found'
  critical:
    description: 'Number of critical severity vulnerabilities'
  high:
    description: 'Number of high severity vulnerabilities'
  medium:
    description: 'Number of medium severity vulnerabilities'
  low:
    description: 'Number of low severity vulnerabilities'
  json-output:
    description: 'Path to the JSON output file (if output-file was specified)'
  badge-url:
    description: >-
      shields.io badge URL. When gist integration is configured, this is a
      dynamic endpoint badge pointing to the gist JSON. Otherwise, it is
      a static shields.io URL. Color indicates severity: green (none),
      yellowgreen (low), yellow (medium), orange (high), red (critical).
  report-url:
    description: >-
      URL to the detailed Markdown scan report stored in the gist.
      Only set when gist-token and gist-id are configured.
      Can be used as the badge link target so clicking the badge
      opens the full vulnerability report.

runs:
  using: 'docker'
  image: 'docker://ghcr.io/tomtonic/grype_me:v1'
