---
name: 'Grype Vulnerability Scanner'
description: 'Scan your repository for vulnerabilities using Anchore Grype'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  scan:
    description: >-
      Specifies what to scan. Can be:
      - 'latest_release': Scan the highest stable version tag (sorted by semantic
        version, not chronological). Pre-release tags (e.g., v1.0.0-beta) are
        skipped in favor of stable releases. Requires at least one tag in the
        repository; use 'head' if your repository has no tags.
      - 'head': Scan the head of the main/default branch
      - A tag name: Scan a specific tag in the repository
      - A branch name: Scan a specific branch in the repository
      Note: Uses local git tags, not the GitHub Releases API. Tags not following
      semantic versioning may not sort as expected.
    required: false
    default: 'latest_release'
  output-file:
    description: 'Path to save JSON scan results (optional)'
    required: false
    default: ''
  variable-prefix:
    description: >-
      Prefix for environment variable names
      (optional, defaults to "GRYPE_")
    required: false
    default: 'GRYPE_'
  debug:
    description: >-
      Enable debug output (prints environment variables when true).
      Warning: may expose sensitive data in logs.
    required: false
    default: 'false'

outputs:
  grype-version:
    description: 'Version of Grype used for scanning'
  db-version:
    description: 'Version of the Grype vulnerability database'
  cve-count:
    description: 'Total number of CVEs found'
  critical:
    description: 'Number of critical severity vulnerabilities'
  high:
    description: 'Number of high severity vulnerabilities'
  medium:
    description: 'Number of medium severity vulnerabilities'
  low:
    description: 'Number of low severity vulnerabilities'
  json-output:
    description: 'Path to the JSON output file (if output-file was specified)'

runs:
  using: 'docker'
  image: 'Dockerfile'
