---
name: Harden runner and checkout
description: Harden GitHub runner (egress audit) and checkout repository
inputs:
  fetch-depth:
    description: Depth of history to fetch
    required: false
    default: '1'
  fetch-tags:
    description: Whether to fetch tags
    required: false
    default: 'false'
  persist-credentials:
    description: Whether to persist the GitHub token in the git config
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        fetch-tags: ${{ inputs.fetch-tags }}
        persist-credentials: ${{ inputs.persist-credentials }}
